### ISSUE TITLE
Изменить имя центрального скрипта на более "правильное". Предлагаю "deployka", как и имя продукта

### ISSUE THREAD

**Issue by artbear** [oscript-library/deployka#1]

**Comment by EvilBeaver** [comment]
а имя deployka разве уже не соответствует?

**Comment by artbear** [comment]
Посмотри на картинку https://files.gitter.im/EvilBeaver/oscript-library/J9Dq/blob
![image](https://cloud.githubusercontent.com/assets/2920817/17662288/1ea9b82e-62ed-11e6-8016-deb2de70b687.png)

и сам увидишь, что писать столь длинное и ничего не значащее имя нет никакого смысла :)

**Comment by artbear** [comment]
Конечно, можно сделать `opm app длиннное-имя` и потом переименовать созданный батник на `deployka.cmd`
Но ИМХО у продукта все должно быть красиво, в т.ч. и базовое имя.
Тем более, что переделать несложно.

Маркетинг и юзабилити, понимаешь :)

**Comment by EvilBeaver** [comment]
картинка устарела. сейчас после установки работает сразу `deployka <параметры>`

**Comment by artbear** [comment]
1 Описания установки и появления `deployka <параметры>` пока не увидел.
2 Андрей, даже разработчику визуально проще работать с deployka.os, чем с длинным-странным именем из шаблона :)

**Comment by nixel2007** [comment]
@artbear 
1. -  вангую, что уже есть в opm

**Comment by EvilBeaver** [comment]
Согласен, имя из шаблона некрасивое

**Comment by artbear** [comment]
> 1 Описания установки и появления `deployka <параметры>` пока не увидел.

@nixel2007 я говорю об описании установки.
Пока ни в доке, ни в тулзах нету ничего, что намекало бы на появление `deployka <параметры>` :)

**Comment by EvilBeaver** [comment]
@artbear в доках этого нет, но вообще, стандартный путь примерно такой:

```
git clone https://github.com/oscript-library/deployka.git
opm build deployka
opm install -f deployka-0.1.1.ospx
```

Пока писал, уже понял, что не очень удобно с номером версии, но это отдельный вопрос.

**Comment by artbear** [comment]
Меня лично как  развертывателя устраивает простейшее развертывание 

```
git clone https://github.com/oscript-library/deployka.git
cd /d deployka/src
opm app имя-скрипта.os deployka.cmd
```

и использование простого `deployka Параметры`

**Comment by EvilBeaver** [comment]
так тоже можно. А после реализации issue можно писать просто `opm app deployka.os`

**Comment by artbear** [comment]
ага, меня как раз и интересует именно этот вариант

**Comment by artbear** [comment]
@EvilBeaver Если даешь добро, могу поменять :)

**Comment by EvilBeaver** [comment]
почему нет, это же опенсорс )
