### ISSUE TITLE
Описка в хелпе

### ISSUE THREAD

**Issue by git22ura** [oscript-library/deployka#11]
Тут должно быть что-то другое в описании. Что-то связанное с "разрешить ворнинги"
https://github.com/oscript-library/deployka/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8E%D0%91%D0%94.os#L30

**Comment by EvilBeaver** [comment]
Дублирует #2 

Спасибо, что сообщили! 👍 В качестве эксперимента можете попробовать сами исправить и прислать PR.
