### ISSUE TITLE
Ошибка в КомандаЗагрузитьКонфигурацию.os

### ISSUE THREAD

**Issue by 1cwin** [oscript-library/deployka#12]
у Функция СтандартныеПараметрыЗапускаКонфигуратора() 
отсутствует "Экспорт" из-за этого выдается ошибка

ОШИБКА - {Модуль C:\OneScript\lib\deployka\src\Классы\КомандаЗагрузитьКонфигурацию.os / Ошибка в строке: 185 / Метод объекта не обнаружен (СтандартныеПараметрыЗапускаКонфигуратора)}

**Comment by artbear** [comment]
@EvilBeaver а Экспорта в `СтандартныеПараметрыЗапускаКонфигуратора` нет в v8runner :)

ИМХО нужно использовать штатный код от v8runner `Конфигуратор.ОбновитьКонфигурацию(...)`
вместо [функции ОбновитьБазуДанных в деплойке](https://github.com/oscript-library/deployka/blob/1bd77412f453356a8e5536eed9c77dc1d4330ae9/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8E.os#L183)

**Comment by EvilBeaver** [comment]
Странно, вот тест https://github.com/oscript-library/deployka/blob/master/tests/ТестКомандаЗагрузитьКонфигурацию.os#L33

**Comment by artbear** [comment]
Проблема при вызове метода `ОбновитьБазуДанных`
в твоем тесте этот метод не вызывается.
ИМХО также не вызывается в методах из этого теста

**Comment by 1cwin** [comment]
http://infostart.ru/webinars/564260/
8.  Евгений Сосна (pumbaE)
Пример запуска https://gist.github.com/pumbaEO/9a52710dfa519c060dc45e9b81b9af5e

был немного переделан в качестве теста... вместо loadrepo был loadcfg ... и собственно наткнулся.
Если бы актуальных где примеров взять)

**Comment by 1cwin** [comment]
еще момент если сюда. 15 Релиз  oscripta при "opm install deployka" ругается на отсутствие прокси и не грузит. магии нет. на 14 релизе все ок.

**Comment by nixel2007** [comment]
@1cwin какой из пятнадцатых релизов оскрипта? :) они пару раз в неделю выходят

**Comment by 1cwin** [comment]
OneScript-1.0.15-setup.exe	Windows Installer (exe)	04.12.2016
вот прям этот

**Comment by EvilBeaver** [comment]
@1cwin как конкретно ругается?

**Comment by EvilBeaver** [comment]
Обновил все пакеты в ночной сборке, теперь, по идее через 5 минут самый свежак должен в дистрибутив попасть.

**Comment by pumbaEO** [comment]
> был немного переделан в качестве теста... вместо loadrepo был loadcfg ... и собственно наткнулся.

а можно пример полной команды привести с loadcfg и какой режим поддержки конфигурации в базе, а так же какая версия платформы?

**Comment by 1cwin** [comment]
ок напишу завтра...

**Comment by pumbaEO** [comment]
просто почему такие вопросы возникли, с 8.3.7 просто так в базу с конфигурацией стоящую на поддержке из командного режиме невозможно загрузить *.cf файл, сначала надо снимать с поддержки и потом только можно сделать без проблем loadcf.

**Comment by 1cwin** [comment]
C:\WINDOWS\system32>deployka loadcfg /fd:\bb\testdb\ c:\deploy\cf /mode -cf -db-user base -db-pwd 123
ОТЛАДКА - Режим обновления: 1
ОТЛАДКА - Путь дистрибутива: c:\deploy\cf
ОШИБКА - {Модуль C:\OneScript\lib\deployka\src\Классы\КомандаЗагрузитьКонфигурацию.os / Ошибка в строке: 185 / Метод объекта не обнаружен (СтандартныеПараметрыЗапускаКонфигуратора)}

**Comment by 1cwin** [comment]
838.2137

**Comment by 1cwin** [comment]
база не на поддержке

**Comment by 1cwin** [comment]
с этой OneScript-1.0.15-setup.exe	Windows Installer (exe)	14.12.2016 ошибок не возникает

**Comment by EvilBeaver** [comment]
Ясно, там был старый опм внутри

**Comment by Infactum** [comment]
Подниму, т.к. ошибка все равно присутствует. Все пакеты актуальны должны быть на текущий момент:
`oscript 1.0.15.260`

```
OneScript Package Manager v0.9.2

Пакеты в системном каталоге библиотек <C:\Program Files (x86)\OneScript\lib>:
1bdd@1.3
1commands@0.8
1testrunner@1.4.1
asserts@0.3.1
cmdline@0.4.1
deployka@0.1.1
fs@0.3
gitrunner@1.0.0
gitsync@1.1
gui@1.0.2.0
InternetMail@1.0.3
json@0.2.1
logos@0.4.1
messenger@1.0.2
notify@0.1.0
opm@0.9.2
oscript-config@0.1.0
packman@0.3
ParserFileV8i@0.0.1
precommit1c@2.0.6
sql@1.0.6206.42769
strings@0.3.1
tempfiles@0.2.1
tool1cd@0.2.1
v8runner@0.6.0
vanessa-runner@0.5.1
yadisk@1.0
```
