### ISSUE TITLE
Не найден путь к платформе 8.3

### ISSUE THREAD

**Issue by Tur8008** [oscript-library/deployka#14]
Добрый день. Спасибо за Ваш труд, очень интересно. Разбираюсь с деплойкой и сразу возникла проблема.
Ввожу с командной строки:
deployka session lock -db accbit

Получаю:
 КРИТИЧНАЯОШИБКА - {Модуль  C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 534 /
Не найден путь к платформе 1С <8.3>}

Каким образом скрипт определяет рабочий каталог платформы? Платформа находится C:\Program Files (x86)\1cv8\

Спасибо!

**Comment by nixel2007** [comment]
По умолчанию ищет как раз в этом каталоге. Проверьте, что в 1cv8 нет пустых каталогов-версий. Могли остаться после удаления платформы.

**Comment by Tur8008** [comment]
Пустых каталогов нет. В одном из каталогов, кстати в максимальной версии, установлен тонкий клиент, соответственно файл 1cv8.exe отсутствует, но судя по коду скрипта в этом случае должно вызываться исключение "Файл 1сv8.exe не существует!". Здесь мы видим нечто иное.

**Comment by EvilBeaver** [comment]
Ну вот оно и не работает. Установите полноценную платформу или используйте ключ с другой версией

**Comment by Tur8008** [comment]
Андрей я еще до обращения сюда пробовал указывать различные маски версии платформы. Результат неизменный. На рабочем ноутбуке была такая же ситуация, но и исключение было другое. Я писал выше. Сейчас поставил специально полную платформу максимальной версией, не работает.

**Comment by EvilBeaver** [comment]
Ну тогда только могу посоветовать расставить отладочных сообщений в коде и выяснить что происходит

**Comment by Tur8008** [comment]
Что и делаю:)

**Comment by Tur8008** [comment]
Все это происходит на боевом терминальном сервере под Win Server 2012R2, поэтому разбираться придется иначе не запустить. А хочется:)

**Comment by ghost** [comment]
@Tur8008 мы используем `v8runner` и её вспомогательные функции 

https://github.com/oscript-library/v8runner#Вспомогательные-и-настроечные-функции

Собственно код вызова https://github.com/oscript-library/deployka/blob/master/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9.os#L16

отсюда и появляется вызов https://github.com/oscript-library/deployka/blob/1bd77412f453356a8e5536eed9c77dc1d4330ae9/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8E.os#L35

в итоге параметр запуска который необходимо указать `-v8version`

суть в том - что Конфигуратор, это как бы толстый клиент. Поэтому нужен `1cv8.exe`

**Comment by Tur8008** [comment]
Алексей, это как раз понятно. Я указываю параметр -v8version. Только результат от этого не меняется. Когда v8runner не находит файл  1cv8.exe возникает другое исключение, что -то вроде файл не существует. Я это видел на своем ноутбуке. Здесь же странное происходит. Версия платформы определяется, а ее рабочий каталог нет.

**Comment by ghost** [comment]
@Tur8008 тут такое дело - я обычно делаю хитро

беру создаю простой скрипт `finder.os`

```
#Использовать v8runner
Конфигуратор = Новый УправлениеКонфигуратором();
Лог = Логирование.ПолучитьЛог("oscript.lib.v8runner");
Лог.УстановитьУровень(УровниЛога.Отладка);
Конфигуратор.ПолучитьПутьКВерсииПлатформы("8.3.9");
```

и дальше начинаю изучать что покажет команда `oscript finder.os`
там в лог выводится [вот место в коде](https://github.com/oscript-library/v8runner/blob/24ab09de76a8a44484355ff4f22fc1e9c73a74d7/src/v8runner.os#L495)

**Comment by Tur8008** [comment]
C:\Users\Администратор\Documents> oscript finder.os
ОТЛАДКА - Читаю конфигурационный файл C:\ProgramData\1C\1CEStart\1CEStart.cfg.
ОТЛАДКА - Читаю конфигурационный файл C:\Users\a.ivanov\AppData\Roaming\1C\1CEStart\1CEStart.cfg.
ОТЛАДКА - C:\Program Files (x86)\1cv8
ОТЛАДКА - C:\Program Files (x86)\1cv82
ОТЛАДКА - Выполняю попытку поиска версии в каталоге C:\Program Files (x86)\1cv8
ОТЛАДКА - Выполняю попытку поиска версии в каталоге C:\Program Files (x86)\1cv82
ОТЛАДКА - Не найдено ни одного каталога с версией.`

**Comment by Tur8008** [comment]
![2017-01-02_22-48-42](https://cloud.githubusercontent.com/assets/9642686/21595342/0b8cce42-d13e-11e6-9c51-0f2e8441a451.jpg)

**Comment by Tur8008** [comment]
Круто, да:)

**Comment by ghost** [comment]
@Tur8008 а давайка версии проверим ;-) oscript

**Comment by Tur8008** [comment]
Я только сегодня 15-ю поставил

**Comment by Tur8008** [comment]
1.0.15.260

**Comment by ghost** [comment]
@Tur8008 смотрю Blame https://github.com/oscript-library/v8runner/blame/24ab09de76a8a44484355ff4f22fc1e9c73a74d7/src/v8runner.os#L495

Вижу что было изменение oscript-library/v8runner#3

Есть предположение, что поломался именно v8runner

**Comment by ghost** [comment]
Так - все еще интересней https://github.com/oscript-library/v8runner/pull/5

**Comment by Tur8008** [comment]
Вижу:) Пока у себя захардкодил это место - которое исключение вызывает и вставил туда путь к платформе
`Если НужныйПуть = Неопределено Тогда
	НужныйПуть = Новый Файл("C:\Program Files (x86)\1cv8\8.3.9.1818\bin\1cv8.exe");
	//ВызватьИсключение "Не найден путь к платформе 1С <"+ВерсияПлатформы+">";
КонецЕсли;`

**Comment by Tur8008** [comment]
Работает, по крайней мере прорвался дальше.

**Comment by Tur8008** [comment]
PS C:\Users\Администратор\Documents> deployka session lock -db accbit
ОТЛАДКА - Действие = lock
ОТЛАДКА - -db = accbit
ОТЛАДКА - Используемый путь для поиска rac C:\Program Files (x86)\1cv8\8.3.9.1818\bin\1cv8.exe
ОТЛАДКА - C:\Program Files (x86)\1cv8\8.3.9.1818\bin\
ОШИБКА - Не указан клиент администрирования
PS C:\Users\Администратор\Documents>

"ОШИБКА - Не указан клиент администрирования" - deployka не может rac найти? Это где должно находиться? Меня смущает путь для поиска равный пути к файлу 1cv8.exe.

**Comment by Tur8008** [comment]
Починил, сделал PR в v8runner.  Алексей спасибо за пример с finder.os, я хоть понял как это дебажить:)
