### ISSUE TITLE
В ветке девелоп неверный текст класса КомандаУправлениеСеансами.os

### ISSUE THREAD

**Issue by artbear** [oscript-library/deployka#24]
Неверный коммит https://github.com/oscript-library/deployka/commit/9a09cdba14f2095678e475752414eb3e9e21cc47#diff-90a48e84a94256555c4ad39f7f2a923aL3

**Comment by artbear** [comment]
И вообще какая-то хрень творится.
Ветки мастер и девелоп в двух репо сильно разъехались :(

где же релизное управление?
чего на самотек все пущено?
![image](https://user-images.githubusercontent.com/2920817/33518669-eefafa42-d7a9-11e7-8896-a323d2782baf.png)

меня на вас нету :)

**Comment by artbear** [comment]
ОФФ только начинаю юзать деплойку после длительного перерыва, и на тебе :(

**Comment by artbear** [comment]
Исправлено в 0.3

**Comment by EvilBeaver** [comment]
Ура! Нам не хватало сильной руки! :)

**Comment by nixel2007** [comment]
угу, поправил только я в итоге =/

**Comment by EvilBeaver** [comment]
@nixel2007 ты жалкий раб нашего господина
