### ISSUE TITLE
Странное поведение блокировки при запуске из под TeamCity

### ISSUE THREAD

**Issue by milanse** [oscript-library/deployka#26]
Запускаю блокировку пользователей 

deployka session lock -db etran-yesterday -db-user %dbUser% -db-pwd %dbPWD% -lockmessage "Работа будет прекращена для обновления конфигурации" -lockuccode "999" -lockstartat 300

При этом в свойствах базы становится

- Блокировка начала сеансов включена.
- Начало и конец пустые
- Код разрешения "a730733e-15c9-44bf-80e3-c0050292abe6"

**Comment by nixel2007** [comment]
Код разрешения, и заполняется гуидом базы, если он не был передан - так из коробки работает деплойка. А вот неработающий lockstartat - это странно. @EvilBeaver есть мысли?

**Comment by EvilBeaver** [comment]
UPD. https://github.com/oscript-library/deployka/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D0%B5%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B8.os#L185

Вот тут только если формат даты какой, 1С не понимает. Других идей нет

**Comment by milanse** [comment]
Покопался, командная строка в rac.exe для блокировки пользователей формируется корректно, но в свойствах базы уже некорректные значения. Наверное к деплойке вопросов нет, можно закрывать.

**Comment by milanse** [comment]
Разобрался.
В команде kill производится повторная блокировка сеансов. т.к. в моем случае блокировка ставится с задержкой по времени 5 мин, затем ожидание и убивание сеансов, то по команде kill я уже не передаю параметры блокировки, соответственно они пустые и код разблокировки = ИД базы. 
А нужна ли блокировка сеансов по команде kill ?

**Comment by EvilBeaver** [comment]
@milanse я не уловил суть. Можете пояснить что имеется в виду?

**Comment by milanse** [comment]
В моем сценарии работы: 

Блокируем работу через 5 мин:

deployka session lock -db %dbName% -db-user %dbUser% -db-pwd %dbPWD% -lockmessage "Работа будет прекращена для обновления конфигурации" -lockuccode "999" -lockstartat 300

 Пауза 5 мин

Убиваем оставшиеся соединения:
deployka session kill -db %dbName% -db-user %dbUser% -db-pwd %dbPWD%

пошло обновление конфигурации

Внутри deployka session kill вызывается УстановитьСтатусБлокировкиСеансов(Истина), но в kill я не передавал параметров блокировки, соответственно все заполняется по-умолчанию.

**Comment by EvilBeaver** [comment]
@milanse ясно. Ну да, непонятно, зачем в kill устанавливается еще и lock. Может @artbear помнит зачем?

**Comment by nixel2007** [comment]
@EvilBeaver скорее всего для того, чтобы не вызвать команду два раза. Иии менять уже наверное поздно, это используется в проде и рассказано в курсе :)

**Comment by EvilBeaver** [comment]
@nixel2007 а в kill можно передавать опции блокировки? Если да, то тогда с деплойкой все хорошо, а если нет - то это баг.

**Comment by artbear** [comment]
я не помню, зачем в кил нужен еще и лок.
недавно даже у Никиты об этом спрашивал.
у меня, например, в ТФС везде килл, затем лок.

**Comment by nixel2007** [comment]
@EvilBeaver можно и нужно. Если их не передавать, то код заполняется гуидом базы, как у ТС.

**Comment by nixel2007** [comment]
@EvilBeaver можно и нужно. Если их не передавать, то код заполняется гуидом базы, как у ТС.

**Comment by EvilBeaver** [comment]
Т.е. это не баг, а фича. Закрываем?
