### ISSUE TITLE
В session lock/unlock добавить возможность блокировки/снятия блокировки регламентных заданий

### ISSUE THREAD

**Issue by 1cgh** [oscript-library/deployka#35]
Обычно на период каких-то операций по развертыванию лочим не только клиентские сеансы, но и регламентные. В deployka сейчас лочатся только клиентские.
Хотелось бы иметь доп. параметр для управления блокировкой РЗ в session lock/unlock

**Comment by EvilBeaver** [comment]
Блокировка сеансов лочит все сеансы, в т.ч. и регламентные
