### ISSUE TITLE
Ошибка в master в КомандаУправлениеСеансами.os

### ISSUE THREAD

**Issue by 1cgh** [oscript-library/deployka#36]
Ошибка в master в КомандаУправлениеСеансами.os
Ну и, соответственно, в хабе в пакете то же самое.

```
Функция ПолучитьСписокРабочихПроцессов()

	КомандаЗапускаПроцессы = СтрокаЗапускаКлиента() + СтрШаблон("process list --cluster=""%1""%2",
	ИдентификаторКластера(), 
	КлючиАвторизацииВКластере()) + " " + мНастройки.АдресСервераАдминистрирования;
	
	Лог.Информация("Получаю список рабочих процессов...");
	СписокПроцессов = ВыполнитьКоманду(КомандаЗапускаПроцессы);
```

Падает на
`СписокПроцессов = ВыполнитьКоманду(КомандаЗапускаПроцессы);
`
Там ожидается коллекция параметров, а передается строка КомандаЗапускаПроцессы

**Comment by EvilBeaver** [comment]
> СписокПроцессов = ВыполнитьКоманду(КомандаЗапускаПроцессы);
Там ожидается коллекция параметров, а передается строка КомандаЗапускаПроцессы

Я вот эту фразу не понял... Что там происходит?

**Comment by 1cgh** [comment]
@EvilBeaver 

https://github.com/oscript-library/deployka/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D0%B5%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B8.os#L441
Функция ПолучитьСписокРабочихПроцессов()
СписокПроцессов = ВыполнитьКоманду(КомандаЗапускаПроцессы);

https://github.com/oscript-library/deployka/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D0%B5%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B8.os#L62
Функция ВыполнитьКоманду(Знач ПараметрыКоманды) Экспорт
ПрочитатьПараметры(ПараметрыКоманды);

https://github.com/oscript-library/deployka/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D0%B5%D0%B0%D0%BD%D1%81%D0%B0%D0%BC%D0%B8.os#L86
Процедура ПрочитатьПараметры(Знач ПараметрыКоманды)
Для Каждого КЗ Из ПараметрыКоманды Цикл

Из ПолучитьСписокРабочихПроцессов() вызывается ВыполнитьКоманду(), откуда уже вызывается ПрочитатьПараметры()

И в ПрочитатьПараметры() ожидается коллекция, а приходит строка

**Comment by 1cgh** [comment]
Получаем
{Модуль C:\Program Files (x86)\OneScript\lib\deployka\src\Классы\КомандаУправлениеСеансами.os / Ошибка в строке: 86 / Значение не является значением объектного типа}

**Comment by EvilBeaver** [comment]
Блин. Это же 100% исправлялось, и давно.

**Comment by EvilBeaver** [comment]
Вот же оно https://github.com/silverbulleters/deployka/pull/5/files

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/42812612-d8f84144-89c6-11e8-9b86-fda378cd874f.png)

**Comment by EvilBeaver** [comment]
а ospx собрался и запушился с библиотеки, походу?

**Comment by nixel2007** [comment]
хз, дженкнисфайл не лежит, значит пушили руками. я не припомню, чтобы публиковал деплойку в последние месяцы.

**Comment by EvilBeaver** [comment]
Я вижу конкретное расхождение кода в двух деплойках... Сейчас попытаюсь собрать воедино

**Comment by EvilBeaver** [comment]
Собрал релиз на базе upstream. Разошедшиеся возможности частично черри-пикнул из os-library, а конфликтующие изменения в классах СерверАдминистрирования и команде управления рег.заданиями оставил в ветке conflicted-scheduler

**Comment by EvilBeaver** [comment]
@1cgh Огромная просьба скачать и посмотреть как работает

**Comment by 1cgh** [comment]
@EvilBeaver реп этот, ветка master?

**Comment by EvilBeaver** [comment]
да

**Comment by EvilBeaver** [comment]
Лучше из opm поставить

**Comment by 1cgh** [comment]
@EvilBeaver у нас всё ок. можем закрыть или еще понаблюдать
пока вот думаем, что делать с https://github.com/oscript-library/deployka/issues/34
аналогичная есть проблема

**Comment by EvilBeaver** [comment]
Ну я там отписался уже. ЕМНИП деплойка убивает и сеансы и соединения, но если соединения обращались в этот момент к СУБД, то они не убиваются. Аналогично происходит и в консоли кластера, так что можно считать это штатным поведением.
