### ISSUE TITLE
Дважды добавлен метод ДобавитьКоманду("scheduledjobs"...

### ISSUE THREAD

**Issue by ramzesvvsu** [oscript-library/deployka#38]
В модуле МенеджерКомандПриложения.os
Процедура ЗарегистрироватьКоманды(Знач Парсер) Экспорт

Дважды добавлен метод
ДобавитьКоманду("scheduledjobs", "КомандаУправлениеСеансами", Парсер);
ДобавитьКоманду("scheduledjobs", "КомандаУправлениеСеансами", Парсер);
![image](https://user-images.githubusercontent.com/21278865/43070869-9deda140-8e79-11e8-9e68-b4cd7c7287cd.png)

**Comment by EvilBeaver** [comment]
Это уже исправлено, не выпустили релиз. Выпущу
