### ISSUE TITLE
deployka loadcfg не работает при отсутствии графики на сервере Linux

### ISSUE THREAD

**Issue by ivankexko** [oscript-library/deployka#52]
Есть сервер под управлением Linux с установленным 1С. При подключении к серверу по ssh при выполнении команды "deployka loadcfg" возникает ошибка:

При **deployka loadcfg**:
ОШИБКА - Получен ненулевой код возврата 255. Выполнение скрипта остановлено!
ОШИБКА - Информации об ошибке нет

При **deployka dbupdate**:
ИНФОРМАЦИЯ - Запускаю обновление конфигурации БД
ОШИБКА - Получен ненулевой код возврата 255. Выполнение скрипта остановлено!
ОШИБКА - Информации об ошибке нет

На сервере нет графики совсем, Иксы не установлены.

Есть рабочее место под управлением Linux с установленным 1С и установленным графическим окружением Cinnamon. На этой машине при выполнении команд **deployka loadcfg** и **deployka dbupdate** ошибок нет, если команды выполняются из графической сессии.
Но если к этой же машине подключиться по ssh, то ошибка повторяется в точности так же. То есть команды выполняются только при активном графическом окружении.

Если подключиться к серверу по ssh в режиме форвардинга иксов, то команды так же не исполняются.

Не всегда есть возможность воспользоваться рабочим местом с установленным графическим окружением. И так же, из-за проявленной ошибки нет возможности использовать надстройку в скриптах автоматизации.

Есть ли какая либо возможность не сталкиваться с описанной ситуацией?

**Comment by ivankexko** [comment]
Похоже это не решаемая проблема:
https://github.com/EvilBeaver/OneScript/issues/1185

**Comment by KamranV21** [comment]
Можно воспользоваться xvfb для эмуляции GUI

**Comment by EvilBeaver** [comment]
> Похоже это не решаемая проблема: [EvilBeaver/OneScript#1185](https://github.com/EvilBeaver/OneScript/issues/1185)

Да, это наличие иксов это требование самой 1С, а не деплойки и/или 1скрипта
