### ISSUE TITLE
Определить контур продукта

### ISSUE THREAD

**Issue by artbear** [oscript-library/deployka#9]
Какие операции входят в контекст продукта, какие не входят?
операции CI будут входить в контур продукта? Например, синтакс-проверка, запуск тестов через хЮнит, БДД; подготовка/очистка временной базы;
подготовка релиза и т.п.

**Comment by artbear** [comment]
ИМХО операции CI лучше включить в контур, т.к.
- идет сильное пересечение операций CI и CD (работа с хранилищем, загрузка конфигурации, работа в режиме предприятия, управление сеансами и т.п.)
- если не включим в продукт команды CI, кто-то другой (например, я :) ) вынужден будет реализовать эти команды в отдельном продукте, что приведет к копипастам, разобщенности и проч.

**Comment by EvilBeaver** [comment]
Нет, тут чисто раскатка и управление сеансами, как я это вижу. Т.е. апдейт системы

Синтаксис и тесты это все-таки еще до попадания в прод должно быть.

**Comment by nixel2007** [comment]
писал в гиттере, напишу здесь. деплойка решает задачи CD. в том числе CD в тестовые базы.
Задачи CI должны решать другие инструменты, например, vanessa-runner отлично справляется с запуском тестов tdd/bdd.

**Comment by artbear** [comment]
А пересекающиеся операции? я уже приводил пример - загрузка конфигурации есть и в CI, и в CD
что с ними делать?

**Comment by ghost** [comment]
@artbear - загрузка куда ?

сервер то у нас называется CI-CD и в его контексте существует как деплойка, так и runner - а мы же идем к тому что это пакеты, поэтому они на сервере CI-CD доступны.

**Comment by ghost** [comment]
если мы говорим - про Доставку на UAT контур, до это деплойка, Если по проверку на контуре и на компьютере разработчика - то это раннер.

раннер - позволяет собрать и проверить, как на сервере CI, так и на компьютере разработчика

**Comment by ghost** [comment]
что мешает вызывать 2 пакета для разных целей.

а вот базовый класс я так понимаю у всех один - пакет v8runner
